# Generated by Django 4.2.1 on 2023-05-23 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
                ('wilaya', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=30)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('image', models.ImageField(upload_to='media')),
                ('categorie', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen', models.CharField(max_length=45)),
                ('temps', models.DateTimeField()),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_tourisme.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='HoraireOuv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.CharField(max_length=255)),
                ('heure_ouverture', models.CharField(max_length=8)),
                ('heure_fermeture', models.CharField(max_length=8)),
                ('lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_tourisme.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_tourisme.user')),
                ('wilayaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_tourisme.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('lieuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_tourisme.lieu')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('lieuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_tourisme.lieu')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_tourisme.user')),
            ],
        ),
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('lieuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_tourisme.lieu')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_tourisme.user')),
            ],
        ),
    ]
