# Generated by Django 4.2.1 on 2023-05-19 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_tourisme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='lieu',
            old_name='type',
            new_name='categorie',
        ),
        migrations.CreateModel(
            name='Transportlieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieuid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_tourisme.lieu')),
                ('transportid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_tourisme.transport')),
            ],
        ),
    ]
