# Generated by Django 4.2.1 on 2023-05-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_tourisme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreciation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='temps',
            field=models.CharField(max_length=8),
        ),
    ]
